# Generated by Django 6.1 on 2026-09-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0010_report_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='signing_authority',
            field=models.CharField(default='Department of Passports, Ministry of Foreign Affairs, Government of Nepal', max_length=150),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('ConnectIPS', 'ConnectIPS'), ('Bank Transfer', 'Bank Transfer'), ('Digital Wallet', 'Digital Wallet'), ('Sandbox Gateway', 'Sandbox Gateway')], default='eSewa', max_length=50),
        ),
    ]
