# Generated by Django 6.1 on 2026-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0011_alter_digitalsignature_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
