# Generated by Django 6.1 on 2026-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0012_alter_applicant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_inspected',
            field=models.BooleanField(default=False, help_text='Tracks whether staff/admin has opened and visually inspected the uploaded document file.'),
        ),
    ]
