# Generated by Django 6.1 on 2026-09-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0013_document_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'NEW'), ('RENEWAL', 'RENEWAL')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
