# Generated by Django 6.1 on 2026-09-13 01:21

import passport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0015_enforce_immediate_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default=passport.models.generate_auth_token, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('ConnectIPS', 'ConnectIPS'), ('Bank Transfer', 'Bank Transfer'), ('Digital Wallet', 'Digital Wallet'), ('Sandbox Gateway', 'Sandbox Gateway'), ('Online', 'Online')], default='eSewa', max_length=50),
        ),
    ]
