# Generated by Django 6.1 on 2026-08-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(default='Nepali', max_length=50),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_taken', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='passport.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='passport.applicant')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to='passport.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('signature_id', models.AutoField(primary_key=True, serialize=False)),
                ('signature_hash', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to='passport.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='passport.application')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=100)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='passport.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_number', models.PositiveIntegerField()),
                ('token_date', models.DateField(auto_now_add=True)),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('queue_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Called', 'Called'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Skipped', 'Skipped')], default='Waiting', max_length=20)),
                ('called_time', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_token', to='passport.application')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='passport.staff')),
            ],
        ),
    ]
